import { FileText, Image as ImageIcon, X, CheckCircle2, XCircle, Volume2, Square, Download, Link2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import { renderSafeMarkdown } from '@/lib/safeMarkdown'

export function AttachmentThumb({ a, onRemove, size = 'md' }) {
  const isImage = a.mimeType?.startsWith('image/')
  const dim = size === 'sm' ? 'h-12 w-12' : 'h-16 w-16'
  return (
    <div className={cn('relative rounded-xl overflow-hidden bg-black/[0.05] dark:bg-white/[0.08] flex items-center justify-center shrink-0 group', dim)}>
      {isImage && a.data ? (
        <img src={`data:${a.mimeType};base64,${a.data}`} alt={a.name} className="h-full w-full object-cover" />
      ) : (
        <div className="flex flex-col items-center gap-1 px-1">
          <FileText size={14} className="text-muted-light dark:text-muted-dark" />
          <span className="text-[8px] text-center leading-tight line-clamp-2 text-muted-light dark:text-muted-dark">{a.name}</span>
        </div>
      )}
      {onRemove && (
        <button onClick={onRemove} className="absolute top-0.5 right-0.5 h-4 w-4 rounded-full bg-black/60 text-white flex items-center justify-center">
          <X size={9} />
        </button>
      )}
    </div>
  )
}

// Renders images the assistant itself generated (via generate_image) — bigger
// and uncropped, unlike the small square AttachmentThumb used for user uploads.
export function GeneratedImages({ images, compact = false }) {
  if (!images?.length) return null
  return (
    <div className="flex flex-col gap-2 mb-2">
      {images.map((img, i) => {
        const src = `data:${img.mimeType};base64,${img.data}`
        return (
          <div key={i} className="relative group rounded-xl overflow-hidden">
            <img src={src} alt="Generated by AI" className={cn('w-full h-auto rounded-xl', compact ? 'max-w-[220px]' : 'max-w-xs')} />
            <a
              href={src}
              download={`air-ai-image-${Date.now()}-${i}.png`}
              className="absolute bottom-1.5 right-1.5 h-7 w-7 rounded-lg bg-black/60 text-white flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
              title="Unduh gambar"
            >
              <Download size={13} />
            </a>
          </div>
        )
      })}
    </div>
  )
}

// Citation links when the assistant answered using live web-search grounding.
export function SourceLinks({ sources, compact = false }) {
  if (!sources?.length) return null
  return (
    <div className="mt-2 pt-2 border-t border-black/[0.06] dark:border-white/[0.08] flex flex-col gap-1">
      <p className={cn('text-muted-light dark:text-muted-dark font-medium', compact ? 'text-[10px]' : 'text-[11px]')}>Sumber:</p>
      {sources.slice(0, 5).map((s, i) => (
        <a
          key={i}
          href={s.url}
          target="_blank"
          rel="noreferrer"
          className={cn('flex items-center gap-1 text-primary-500 hover:underline truncate', compact ? 'text-[10px]' : 'text-[11px]')}
        >
          <Link2 size={compact ? 9 : 10} className="shrink-0" />
          <span className="truncate">{s.title}</span>
        </a>
      ))}
    </div>
  )
}

export function ActionChips({ actions }) {
  if (!actions?.length) return null
  return (
    <div className="flex flex-col gap-1 mb-2">
      {actions.map((a, i) => (
        <div
          key={i}
          className={cn(
            'flex items-center gap-1.5 text-xs px-2.5 py-1.5 rounded-lg animate-pop',
            a.ok ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' : 'bg-rose-500/10 text-rose-500'
          )}
        >
          {a.ok ? <CheckCircle2 size={13} className="shrink-0" /> : <XCircle size={13} className="shrink-0" />}
          <span>{a.message}</span>
        </div>
      ))}
    </div>
  )
}

// Renders one chat bubble (both user and assistant). `compact` tightens
// padding/text size for the floating widget's smaller panel.
// `onSpeak`/`isSpeaking`/`speechSupported` wire up the per-bubble "read
// aloud" control on assistant messages (optional — omit to hide it).
export function MessageBubble({ m, compact = false, onSpeak, isSpeaking = false, speechSupported = false }) {
  return (
    <div className={cn('flex animate-fade-in', m.role === 'user' ? 'justify-end' : 'justify-start')}>
      <div className={cn(
        'max-w-[85%] rounded-2xl leading-relaxed',
        compact ? 'px-3 py-2 text-[13px]' : 'px-4 py-2.5 text-sm',
        m.role === 'user' ? 'bg-primary-500 text-white rounded-br-md' : m.isError ? 'bg-rose-500/10 text-rose-500 rounded-bl-md' : 'bg-black/[0.05] dark:bg-white/[0.07] rounded-bl-md'
      )}>
        {m.attachments?.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-2">
            {m.attachments.map((a, i) => a.data ? (
              <AttachmentThumb key={i} a={a} size={compact ? 'sm' : 'md'} />
            ) : (
              <span key={i} className="flex items-center gap-1 text-[11px] px-2 py-1 rounded-lg bg-black/10 dark:bg-white/15">
                {a.mimeType?.startsWith('image/') ? <ImageIcon size={11} /> : <FileText size={11} />} {a.name}
              </span>
            ))}
          </div>
        )}
        {m.role === 'assistant' && <ActionChips actions={m.actions} />}
        {m.role === 'assistant' && <GeneratedImages images={m.generatedImages} compact={compact} />}
        {m.text && (
          m.role === 'assistant' ? (
            <div
              className="whitespace-pre-wrap [&_strong]:font-semibold [&_em]:italic [&_code]:bg-black/10 dark:[&_code]:bg-white/10 [&_code]:px-1 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-[13px] [&_ul]:list-disc [&_ul]:pl-4 [&_ol]:list-decimal [&_ol]:pl-4 [&_p]:mb-2 last:[&_p]:mb-0 [&_a]:text-primary-500 [&_a]:underline"
              dangerouslySetInnerHTML={{ __html: renderSafeMarkdown(m.text) }}
            />
          ) : (
            <p className="whitespace-pre-wrap">{m.text}</p>
          )
        )}
        {m.role === 'assistant' && <SourceLinks sources={m.sources} compact={compact} />}
        {m.role === 'assistant' && !m.isError && m.text && speechSupported && (
          <button
            onClick={() => onSpeak?.(m.id, m.text)}
            title={isSpeaking ? 'Berhenti' : 'Dengarkan'}
            className={cn(
              'mt-1.5 flex items-center gap-1 text-[11px] transition-colors',
              isSpeaking ? 'text-primary-500' : 'text-muted-light dark:text-muted-dark hover:text-primary-500'
            )}
          >
            {isSpeaking ? <Square size={10} className="fill-current" /> : <Volume2 size={12} />}
            {isSpeaking ? 'Berhenti' : 'Dengarkan'}
          </button>
        )}
      </div>
    </div>
  )
}
